### ISSUE TITLE
how to enable codec for h264

### ISSUE THREAD

**Issue by ewolfox** [Javernaut/ffmpeg-android-maker#15]
i am confused.  now i want to enable the h264 encode.  how?

**Comment by Javernaut** [comment]
Hi @ewolfox ,

As I understood your question you need a h264 encoder.

I explicitly disable all encoders for FFmpeg, because I don't need them. It is done by [--disable-encoders](https://github.com/Javernaut/ffmpeg-android-maker/blob/master/scripts/ffmpeg/build.sh#L47) flag. FFmpeg supports h264 decoding out-of-the-box, however I'm not sure about encoding.

First, try removing that flag and check if it works for you.

If not, you may need an external library such as [x264](https://www.videolan.org/developers/x264.html) or [OpenH264](https://www.openh264.org). The guidance of how to integrate a new external library can be found [here](https://github.com/Javernaut/ffmpeg-android-maker/wiki/External-libraries-integration).

Beware, that using x264 upgrades the FFmpeg license to GPL. You will also need to pass the `--enable-gpl` flag to FFmpeg's configure script in this case.

**Comment by ewolfox** [comment]
Thank you very much.

**Comment by e1001925** [comment]
I tried. It works.

**Comment by tobias-r** [comment]
Hi! I am still confused, @e1001925, what exactly did you do?
