### ISSUE TITLE
why replace LD with CC?

### ISSUE THREAD

**Issue by fengguangle** [Javernaut/ffmpeg-android-maker#27]
your scripts:
export FAM_LD=${FAM_CC}
export FAM_AS=${FAM_CC}

usually:
export LD=$TOOLCHAIN/bin/$TARGET-ld
export AS=$TOOLCHAIN/bin/$TARGET-as

when I change FAM_LD and FAM_AS to real path to ld and as, can not build!
What's wrong and why？

**Comment by fengguangle** [comment]
I found that the ld of llvm is also GNU ld，maybe clang can act as GNU ld?

**Comment by Javernaut** [comment]
Hello @fengguangle ,
Sorry for the very long time to reply.
I faced issues with llvm linker and clang appears to be a multitool. I accepts C code, asm files and even acts like a linker. So I decided to use it instead of the llvm linker directly.
But anyway, GNU binutils are deprecated in Android NDK and soon I will need to migrate to llvm completely.
