### ISSUE TITLE
How to run FFMPEG command using cpp Android?

### ISSUE THREAD

**Issue by nihkilft123** [Javernaut/ffmpeg-android-maker#37]
We build whole library as per your script and suggestion, but what after that. We need to run our all complex command on it! Than how we can write cpp code for Android? What is the code to run FFMPEG command? Your example is only contains how to get video frames, but what if we need execute our command like other libraries built by popular **tanersener, bravobit** etc...

**Comment by Javernaut** [comment]
The main feature of this project is the configurability of the building process. You have full control over how the libraries are compiled and what actual libraries are compiled. I see this project as slightly lower level than tanersener's and bravobit's because I presume direct working with FFmpeg API and not executing a command as you would do in a terminal. I consider adding support for it somewhere in the future.

If you want to execute commands like in desktop terminal then you will need the `ffmpeg` binary (or program). It can be compiled from sources too. It has to be packaged with *.so files as the `ffmpeg` binary is just a facade for them.
This works actually, but it isn't the main course for this project.

If the app size isn't your priority and if you don't want to work with FFmpeg C API directly then using tanersener's or bravobit's repos will be a better solution.

**Comment by nihkilft123** [comment]
I know that there is some already available libraries in github like bravobit's, tanersener's and also microshow's. These all have certain limitations like some of this will not work for target SDK 29 & 30 and tanersener's lib is good but there is problems with -filter_complex command's output and micrshow's lib is crashing in android 10 and 11 beta! So, all have specific problems. So, I am considering to create own one.

Look at [this question](https://stackoverflow.com/q/63610485/13846544) for my deep need.
