### ISSUE TITLE
andidate function has type mismatch at 2nd parameter

### ISSUE THREAD

**Issue by raiarpit** [Javernaut/ffmpeg-android-maker#47]
Hi, while building n4.1.4 as shown in example, I get the following error

/22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/bits/ioctl.h:60:5: note: candidate function has type mismatch at 2nd parameter (expected 'unsigned long' but has 'unsigned int')

My ndk version is 22.1.7171670. If I understand correctly, it has got something to do with the fact that gcc isn't supported by ndk anymore.

Hence, I downloaded an older version of ndk (r13b) and tried to run the script. 

Then I got the following error

Library/Android/sdk/ndk/android-ndk-r13b/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang is unable to create an executable file

**Comment by Javernaut** [comment]
Hello.

I feel a bit nostalgic about this issue. Grab a drink and hear a story.

### ioctl.h problem

When I first tried to make the FFmpeg compilable, even before I decided to make it public, I tried using FFmpeg 4.1. I finally made it compilable, however some problems (like in your message) were eliminated by disabling certain modules of FFmpeg from being compiled at all. Even now the [what-the-codec](https://github.com/Javernaut/ffmpeg-android-maker/tree/what-the-codec) branch still has such modules disabled and the brief check of FFmpeg 4.1.4 with it [works fine](https://github.com/Javernaut/ffmpeg-android-maker/actions/runs/692397221). Check [this file](https://github.com/Javernaut/ffmpeg-android-maker/blob/what-the-codec/scripts/ffmpeg/build.sh) to see what is actually disabled.

Now the master branch has all standard modules enabled.

Specifically your problem was fixed by [this](https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/73251678c83cbe24d08264da693411b166239bc7) commit, but it was merged only into FFmpeg 4.2.
This means that if you want all modules of FFmpeg being compiled, please use the FFmpeg 4.2+. If you are ok with certain modules not included to the final binary, try disable them. I don't really remember which modules give this error.

###  NDK issue

The Android NDK is an evolving beast and it is very important to use its proper version for this scrip to work. Supported versions are r19 - r21.
Starting with NDK r19 it has unified directory for header files, which simplifes a lot of things. Previously the easiest way for compilation was to create a standalone toolchain for each of the ABI you are targeting. All NDK versions up until r21e are checked and work well with the script. But the r22 isn't supported yet. It is planned for the future. This information is in the README.md file.

I suggest using r21e as the LTS version of NDK.

**Comment by raiarpit** [comment]
First of all, man the reply was extremely swift. Truly appreciate that. I can make out that this project is really close to your heart.

Now to other extremely important topic, I doubt you will be travelling to India anytime soon. But I would still like to buy you a beer! Can you please share a link somewhere through which I could :)

I am checking the resources you mentioned here, and will be playing around a lot. this is a great starting point.

**Comment by Javernaut** [comment]
Thanks for the kind words and let's better stay sober :)
Is your issue resolved now?

**Comment by raiarpit** [comment]
haha, sure thing. So yes, its kinda resolved. I am going to close this one, will post another query if needed
