### ISSUE TITLE
ffmpeg  cannot executable  at android

### ISSUE THREAD

**Issue by DorisGM** [Javernaut/ffmpeg-android-maker#49]
I tried to exex ffmpeg at android cmd. but  I got follow error.
Enviorment：
Ubuntu 16.04 
NDK version:  r22b
ffmpeg version: 4.4

05-27 00:43:59.098 +0000 22178 22178 W linker  : /data/data/com/files/ffmpeg: unsupported flags DT_FLAGS_1=0x8000001
--------- beginning of crash
05-27 00:43:59.098 +0000 22178 22178 F libc    : CANNOT LINK EXECUTABLE "/data/user/0/com/files/ffmpeg": library "libavdevice.so" not found
05-27 00:43:59.098 +0000 22178 22178 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 22178 (ffmpeg)

**Comment by Javernaut** [comment]
Well, seems like your binary doesn't see the libavdevice.so library. Did you move it with the ffmpeg binary?

Long ago I actually managed to make ffmpeg binary work in android's terminal, but I don't remember how exactly. Probably all libraries were built as static and there was only one single ffmpeg binary that contained all dependencies. This way I eliminated the 'so no found' error.

**Comment by Javernaut** [comment]
Maybe in future I'll work on this issue and prepare instuctions to make a properly usable ffmpeg binary for android cmd.
But isn't my focus for now.

**Comment by DorisGM** [comment]
> Maybe in future I'll work on this issue and prepare instuctions to make a properly usable ffmpeg binary for android cmd.
> But isn't my focus for now.

Thanks for your reply. I already fixed it.  It need  to configure  enable-static . default is disable-static.

**Comment by Javernaut** [comment]
So I remember the solution correctly, nice :)

**Comment by guilhermesgb** [comment]
Hello, thanks for this project, it's really coming in handy.

Could you guys (@Javernaut or @DorisGM) share the details of how to tweak the current setup as to build FFmpeg statically? Thanks in advance!

**Comment by guilhermesgb** [comment]
I also managed to tweak it to get it work. Here's the changes I had to do, for future reference (changes to 94d703c8598940cfb90015ed663aad2a807cf228, a commit in master from Feb 20):

In the `scripts/ffmpeg/build.sh` file,
* comment out/remove the `--enable-shared` and `--disable-static` flags from the configure call, so that the build process builds FFmpeg statically including its dependencies in a single standalone executable file.

In the `ffmpeg-android-maker.sh` file,
* in the function prepareOutput(), replace the `*.so` for `*.a`, as *.so files won't be generated.
* then, in the very bottom of the script, comment out the `checkTextRelocations || exit 1` line so we skip this step altogether.
