### ISSUE TITLE
Clang Error: No input Files

### ISSUE THREAD

**Issue by oluwabajio** [Javernaut/ffmpeg-android-maker#70]
Hello.

I triend to build ffmpeg libraries, but i am getting the error:  

`Building the component: ffmpeg
/mnt/c/Users/oluwa/AppData/Local/Android/Sdk/ndk/25/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android19-clang is unable to create an executable file.
C compiler test failed.`

Then i checked the file:  /sources/ffmpeg/ffmpeg-5.1/ffbuild/config.log, and this is the error shown at the last line.

`BEGIN /tmp/ffconf.L2VWMss7/test.c
    1   int main(void){ return 0; }
END /tmp/ffconf.L2VWMss7/test.c
/mnt/c/Users/oluwa/AppData/Local/Android/Sdk/ndk/25/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android19-clang --sysroot=/mnt/c/Users/oluwa/AppData/Local/And>clang: error: no input files
C compiler test failed.`

I have tried all Ndk versions  from NDK21 to NDK25, but i get the same error. 

i am using WSL 2 on windows 11. With Ubuntu 20.04.  I also upgraded ubuntu version to 22.04, and i still get the same error.
![export](https://user-images.githubusercontent.com/13810874/209453244-dddcc305-a8a7-43a5-99ea-3435cc733a07.png)

**Comment by Javernaut** [comment]
Hello guys, sorry for such a long delay.

I've checked WSL 2 on Windowns 11 today and can confirm it actually works. However, there are certain important thing to consider:
- You have to point ANDROID_SDK_HOME and ANDROID_NDK_HOME to **Linux** versions of the SDK and NDK.
- You have to preinstall certain software into your Linux subsystem. What exact software to install, how to do it and how to install the sdk and its necessary packages you can find out in the [Dockerfile](https://github.com/Javernaut/ffmpeg-android-maker/blob/development/tools/docker/Dockerfile). Beware, you may need to install jdk 11 instead of jdk 8.

Apart from that I can recommend the [Docker](https://github.com/Javernaut/ffmpeg-android-maker/wiki/Docker-support) tool for ffmpeg-android-maker execution on Windows.
