### ISSUE TITLE
/bin/sh: 1: cd: can't cd to /mnt/ffmpeg-android-maker

### ISSUE THREAD

**Issue by MmingY** [Javernaut/ffmpeg-android-maker#83]
I encountered an issue while running in docker, which is the error "/bin/sh: 1: cd: can't cd to /mnt/ffmpeg-android-maker".

**Comment by Javernaut** [comment]
Hey @MmingY ,

Can you give me an example of the command you use for docker execution? Specifically I'm interested in how you provide the ffmpeg-android-maker directory from your machine to the container.

**Comment by MmingY** [comment]
Hey,
This is the command I used.
```shell
docker run --rm -v D:\FFmpeg-build\ffmpeg-android-maker:/mnt/ffmpeg-android-maker javernaut/ffmpeg-android-maker
``` 
I haven't solved this problem, but I created an Ubuntu environment and downloaded your script, which can compile what I want

**Comment by Javernaut** [comment]
Glad that the WSL is helpful.

Also, thanks for a heads-up regarding possible problems with the Docker image invocation on Windows machine. Will be able to check it out in a couple of weeks, as my Windows machine is pretty far from me right now.

**Comment by Javernaut** [comment]
Finally got to my WIndows machine. I have checked the freshly pulled image with such a command:
```
docker run --rm -v D:\Development\FFmpeg\ffmpeg-android-maker-master:/mnt/ffmpeg-android-maker -e FAM_ARGS="-abis=arm" javernaut/ffmpeg-android-maker
```
and everything worked flawlessly.

It is hard to tell why in your case the directory wasn't mounted properly. Probably the Docker logs have to be checked, maybe there is some hint there. Maybe updating the Docker app would be helpful. Or retyping the path to mount.

Meanwhile, since the docker image actually worked on Windows machine, I'm closing this issue.
