### ISSUE TITLE
Vulkan support for ffmpeg 6.1

### ISSUE THREAD

**Issue by streamingdv** [Javernaut/ffmpeg-android-maker#85]
Hi, this is just a question, I'm currently try to add vulkan support for ffmpeg/ javacv which was added in ffmpeg 6.1 all builds for Linux, MacOS, Windows are currently passing but I have major difficulties to make the Android builds pass. In Ndk 26 I saw that the headers which are used are still old (e.g. 237) so I'm not even sure if NDK 26 officially supports to build ffmpeg 6.1 with vulkan support? Do you have any experience with that? I saw that you have disabled vulkan explicitly.

**Comment by Javernaut** [comment]
Hello @streamingdv .

I'm afraid I don't have much experience with Vulkan yet. Indeed in the past (I believe during my ndk r26 or ffmpeg 6.0 tests for this repo) I had to explicitly disable the vulkan support, because it was autodetected to 'true' and that caused the build failure. However, right now with ffmpeg 6.1 and ndk r26b seem to autodetect the flag to 'false'. So simple removing the `--disable-vulkan` flag will not build the vulkan module.

As for old Vulkan versions in ndk, you are right. ffmpeg 6.1 looks for vulkan 255, as I understand.

I can tell you one more fact. According to [Android documentation](https://developer.android.com/games/optimize/vulkan-get-started#android-version) not all Android devices now support vulkan 1.3. Moreover:

> Android platform support for a Vulkan API version does not guarantee the API version is supported by the device's Vulkan driver. A device running Android 13 might only support version 1.1 of the Vulkan API.

I have a research on the matter planned, but for a quite distant future.

**Comment by streamingdv** [comment]
Okay thanks, yes that's what I thought, it's maybe a bit to early to enable these features for Android. Vulkan decoding was introduced in ffmpeg 6.1.0 so I think we have to wait. We proceeded now to enable Vulkan for other builds (Windows, Mac, Linux) expect for Android :)

I think I'll definitely come back to it in the future. Thanks for the all the information.
